language: python

python:
  - '2.7'

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

install:
  - npm install
  - npm install -g grunt-cli
  - pip install -r requirements.txt
  - pip install selenium

script:
  - grunt jshint
  - python centralserver/manage.py test -v 2 --traceback

notifications:
  slack: learningequality:hMBsdQ11UhIEcw8GPXlf9n1B
