dist: xenial

language: python

sudo: false

python:
  - '2.7'

services:
  - docker
  - xvfb

env:
  global:
  - MOZ_HEADLESS=1
  - PATH="$PATH:/home/travis/bin"

install:
  - make assets
  - pip install -r requirements_test.txt
  - wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
  - gunzip -c geckodriver.tar.gz | tar xopf -
  - chmod +x geckodriver
  - mkdir -p /home/travis/bin
  - mv geckodriver /home/travis/bin

script:
  - coverage run manage.py test ab_testing central i18n registration -v 2 --traceback

after_success:
  - codecov
