language: python
python:
- '2.7'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
install:
- pushd $TRAVIS_BUILD_DIR; npm install; popd
- pushd $TRAVIS_BUILD_DIR; npm install -g grunt-cli; popd
- pushd $TRAVIS_BUILD_DIR; pip install -r requirements.txt; popd
script:
- grunt jshint
- python centralserver/manage.py test -v 2 --traceback

notifications:
  slack: learningequality:hMBsdQ11UhIEcw8GPXlf9n1B
