language: python

sudo: false

python:
  - '2.7'

services:
  - docker

env:
  - MOZ_HEADLESS=1

before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
    --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

install:
  - make assets
  - pip install -r ka-lite-submodule/requirements_test.txt
  - pip install --upgrade selenium  # Upgrade Selenium because we don't want to change the 0.16.x sub module

# See: https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python centralserver/manage.py test ab_testing -v 2 --traceback
  - python centralserver/manage.py test central -v 2 --traceback
  - python centralserver/manage.py test contact -v 2 --traceback
  - python centralserver/manage.py test faq -v 2 --traceback
  - python centralserver/manage.py test i18n -v 2 --traceback
  - python centralserver/manage.py test registration -v 2 --traceback
