language: python

sudo: false

python:
  - '2.7'

services:
  - docker

env:
  global:
  - MOZ_HEADLESS=1
  - PATH="$PATH:/home/travis/bin"

before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
    --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

install:
  - make assets
  - pip install -r requirements_test.txt
  - wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz
  - gunzip -c geckodriver.tar.gz | tar xopf -
  - chmod +x geckodriver
  - mkdir -p /home/travis/bin
  - mv geckodriver /home/travis/bin

# See: https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - export PATH="$PATH:/home/ubuntu/bin"

script:
  - python manage.py test ab_testing -v 2 --traceback
  - python manage.py test central -v 2 --traceback
  - python manage.py test i18n -v 2 --traceback
  - python manage.py test registration -v 2 --traceback
